---
wandb_attack_run: AttacksHaircolorGender/kz2mbctl # WandB run id for attack that should be evaluated
stylegan_model: stylegan2-ada-pytorch/ffhq.pkl # Path to StyleGAN2 weight.

seed: 42

image_location: 'wandb-weights' # 'local' if images already downloaded to media/images, 
                                # 'wandb-media' to download from run, 
                                # 'wandb-weights' to generate from weight vector if media is not stored on wandb


prompts: [["a man",  "a woman"],
          ["a boy",  "a girl"],
          ["a male face",  "a female face"]]

rtpt: # State RTPT details. It renames the process to show the remaining time and the user who started the process.
  experiment_name: Attribute identification
  name_initials: AM


wandb: # Options for WandB logging.
  enable_logging: true # Activate logging. 
  wandb_init_args: # WandB init arguments.
    project: Tests
    save_code: true
    name: 

