---
wandb_attack_run: model_inversion_attacks/opwhz4h0 # WandB run id for attack that should be evaluated
stylegan_model: stylegan2-ada-pytorch/ffhq.pkl # Path to StyleGAN2 weight.

seed: 42


#prompts


rtpt: # State RTPT details. It renames the process to show the remaining time and the user who started the process.
  experiment_name: Attribute identification
  name_initials: AM


wandb: # Options for WandB logging.
  enable_logging: true # Activate logging.
  wandb_init_args: # WandB init arguments.
    project: attribute_identification
    save_code: true
    name: test
