---
wandb_target_run: model_inversion_targets/9f2xjkxb
wandb_evaluation_run: model_inversion_evaluation/revpy2ls
stylegan_model: stylegan2-ada-pytorch/ffhq.pkl
seed: 42
dataset: celeba_attr

candidates:
  num_candidates: 200
  candidate_search:
    search_space_size: 5000
    center_crop: 800
    resize: 224
    horizontal_flip: true
    batch_size: 25
    truncation_psi: 0.5
    truncation_cutoff: 8

attack:
  batch_size: 25
  num_epochs: 70
  targets: all
  discriminator_loss_weight: 0.0
  single_w: true
  clip: false
  transformations:
    CenterCrop:
      size: 800
    Resize:
      size: 224
      antialias: true
    RandomResizedCrop:
      size: [224, 224]
      scale: [0.9, 1.0]
      ratio: [1.0, 1.0]
      antialias: true

  optimizer:
    Adam:
      lr: 0.005
      weight_decay: 0
      betas: [0.1, 0.1]

final_selection:
  samples_per_target: 5 #set back to 50
  approach: transforms
  iterations: 10 # setback to 100


wandb:
  enable_logging: true
  wandb_init_args:
    project: model_inversion_attacks
    save_code: true
    name: Attack_Beard_Or